### PR TITLE
move accelerate to `dev.dependencies`

### PR DESCRIPTION
**Pull request by tadamcz**
`accelerate` isn't required for `repeng` to work. Including it in the main dependencies section imposes an unnecessary version constraint that can lead to conflicts.

Tests pass with this change, but I didn't do any further manual checking.

### CODE REVIEW

**Comment by vgel** [comment]
why was it included originally i wonder :-? should we just remove it? or make it an optional dependency?

**Comment by vgel** [comment]
i think it's needed for https://github.com/vgel/repeng/blob/main/notebooks/llama370b.ipynb (`device_map="auto"`), so maybe we could just remove it as a dependency and install it there manually? i'll test.

**Comment by tadamcz** [comment]
Does `device_map=auto` inherently require `accelerate`, even if you don't want to use multiple GPUs?

**Comment by tadamcz** [comment]
> Does device_map=auto inherently require accelerate, even if you don't want to use multiple GPUs?

Never mind: yes it does!

**Comment by vgel** [comment]
#56 removes accelerate entirely from deps--my current feeling is that users should install it manually if they need that functionality.

**Comment by tadamcz** [comment]
Perfect, thanks!

**Pull request closed without merging**
